# Generated by Django 5.2 on 2025-04-25 00:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '결제 대기'), ('paid', '결제 완료'), ('shipping', '배송 중'), ('delivered', '배송 완료'), ('cancelled', '주문 취소')], default='pending', max_length=20, verbose_name='주문상태')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 금액')),
                ('payment_method', models.CharField(choices=[('card', '신용카드'), ('bank_transfer', '계좌이체'), ('mobile', '휴대폰 결제'), ('virtual_account', '가상계좌')], max_length=20, verbose_name='결제 방법')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='수령인')),
                ('recipient_phone', models.CharField(max_length=15, verbose_name='연락처')),
                ('shipping_address1', models.CharField(max_length=200, verbose_name='기본주소')),
                ('shipping_address2', models.CharField(blank=True, max_length=200, verbose_name='상세주소')),
                ('shipping_zip_code', models.CharField(max_length=10, verbose_name='우편번호')),
                ('shipping_note', models.CharField(blank=True, max_length=200, verbose_name='배송메모')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='결제 ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품 목록',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '장바구니 상품',
                'verbose_name_plural': '장바구니 상품 목록',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
